spring.application.name=student-project-portal

server.port=8082

# Connect to your Docker MySQL container
spring.datasource.url=jdbc:mysql://db:3306/project_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Settings (Automatically creates/updates tables in Docker)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
